preload = $HOME/Wallpapers/KAITOthighs.png
preload = $HOME/Wallpapers/014 - h3p0 (15875092).png
wallpaper = DVI-D-1, $HOME/Wallpapers/KAITOthighs.png
wallpaper = DP-1, $HOME/Wallpapers/014 - h3p0 (15875092).png

