[package]
name = "workspaces"
version = "0.1.0"
edition = "2024"

[dependencies.json]
version = "0.12.4"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"
