general {
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
}

animations {
    enabled = true
    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    bezier = easeInOutCubic, 0.645, 0.045, 0.355, 1

    animation = fadeIn, 1, 4, easeOutQuint
    animation = fadeOut, 1, 4, easeOutQuint
    animation = inputFieldDots, 1, 3, easeOutQuint
}

background {
    monitor = 
    path = screenshot
    blur_passes = 3
    blur_size = 6
    noise = 0.02
    contrast = 0.9
    brightness = 0.6
    vibrancy = 0.2
}

label {
    monitor = 
    text = 󰀉  $USER
    font_family = FiraCode Nerd Font
    color = rgba(242, 242, 242, 0.8)
    font_size = 16
    
    position = 0, 140
    halign = center
    valign = bottom
}

# INPUT FIELD
input-field {
    monitor = 
    size = 280, 50
    outline_thickness = 1
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    
    inner_color = rgba(255, 255, 255, 0.05)
    outer_color = rgba(255, 255, 255, 0.15)
    check_color = rgba(255, 255, 255, 0.3)
    fail_color = rgba(255, 85, 85, 0.5)
    
    font_color = rgba(242, 242, 242, 0.9)
    font_family = FiraCode Nerd Font
    fade_on_empty = false
    rounding = 16

    placeholder_text = <span foreground="##a6a6a6">󰌾 Password...</span>

    position = 0, 80
    halign = center
    valign = bottom
}

# LAYOUT LABEL
label {
    monitor = 
    text = $LAYOUT[EN,RU]
    font_family = FiraCode Nerd Font
    color = rgba(242, 242, 242, 0.4)
    font_size = 11
    halign = center
    valign = bottom
    position = 0, 50
}

# TIME LABEL
label {
    monitor = 
    text = cmd[update:1000] echo "<b>$(date +"%H:%M")</b>"
    color = rgba(242, 242, 242, 0.75)
    font_family = FiraCode Nerd Font
    font_size = 90
    position = 0, 100
    halign = center
    valign = center
}

# DATE LABEL
label {
    monitor = 
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(242, 242, 242, 0.4)
    font_family = FiraCode Nerd Font
    font_size = 16
    position = 0, 30
    halign = center
    valign = center
}
