# Wallpaper directory in $HOME/Wallpapers
$mainMod = SUPER
$mainExt = SUPER ALT
$mainSt = SUPER SHIFT

$imageViewer = vulkan_zero

$apps = rofi -show drun
$browser = firefox

exec-once = hyprctl setcursor Notwaita-Gray 24

# execr = hyprpaper & ~/.local/share/eww/eww open -c /mnt/Programming/Projects/yuck/main_bar topbar
exec-once = /usr/bin/quickshell
exec = hyprpaper

monitor = DP-1, 1920x1080@180.00, 0x0, 1
monitor = DVI-D-1, 1366x768, -1366x312, 1

gesture = 3, vertical, workspace

# -------------------------------- SOURCES --------------------------------
source = options.conf
source = input.conf
source = windowrules.conf
