windowrule = workspace 2, match:class waterfox
windowrule = workspace 2, match:class firefox
windowrule = workspace special:telegram, match:class org.telegram.desktop
windowrule = workspace 10, match:class discord
windowrule = workspace 10, match:class vesktop
windowrule = workspace 6, match:class jetbrains-rider
windowrule = workspace 7, match:class osu!
windowrule = workspace 9, match:class obsidian
windowrule = workspace special:spec silent, match:class Transfer.Game.Tests
windowrule = workspace special:spec silent, match:class OsuMaps.App.Tests

windowrule = float true, pin on, match:class viewer
windowrule = float true, match:class imv

windowrule=float on, rounding 15, size 1024 768, opacity 1, match:class ^thunar$

workspace = 11s[true], defaultName:spec
workspace = 12s[true], defaultName:telegram

layerrule = blur on, match:namespace widget
layerrule = blur on, dim_around on, match:namespace rofi
layerrule = dim_around on, match:namespace focusableApps
