bar:
  height: 30
  location: top
  background: 00000077

  font: HurmitNerdFontMono:pixelsize=15:weight=bold

  center:
    - clock:
        time-format: "%H:%M"
        content:
          - string:
              text: "{time}"
              foreground: ddddddff
              margin: 6

  right:
    - battery:
        name: ${BATTERY}
        poll-interval: 30000
        content:
          map:
            conditions:
              state == "unknown": {empty: {}}
              capacity < 30:
                string:
                  margin: 10
                  text: "BAT: {capacity}%"
                  deco:
                    background:
                      color: ff0000ff
              capacity > 30:
                string:
                  margin: 10
                  text: "BAT: {capacity}%"
    - label:
        content:
          string:
            text: "|"
            margin: 10
    - niri-language:
        content:
          - string: 
              text: "{language}"
              margin: 10
              foreground: ddddddff
  
  left:
    - mem:
        poll-interval: 2500
        content:
          map:
            conditions:
              percent_used >= 80:
                string: 
                  margin: 10
                  text: "MEM: {percent_used}%"
                  deco:
                    background:
                      color: ff0000ff
              percent_used < 80:
                string: 
                  margin: 10
                  text: "MEM: {percent_used}%"
    - label:
        content:
          string:
            text: "|"
            margin: 10
    - cpu:
        poll-interval: 1000
        content:
          map:
            conditions:
              id < 0:
                - string: 
                    text: "CPU: {cpu}%"
                    margin: 10
                    foreground: ddddddff
    - label:
        content:
          string:
            text: "|"
            margin: 10
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: 
                    text: "APP: {app-id}"
                    margin: 10
                    foreground: ddddddff
