bar:
  height: 30
  location: top
  background: 00000077

  font: 0xProtoNerdFont:pixelsize=16:weight=bold

  center:
    - clock:
        time-format: "%H:%M"
        content:
          - string:
              text: "{time}"
              foreground: ddddddff
              margin: 6

  right:
    - niri-language:
        content:
          - string: 
              text: "{language}"
              margin: 30
              foreground: ddddddff
  
  left:
    - cpu:
        poll-interval: 1000
        content:
          map:
            conditions:
              id < 0:
                - string: 
                    text: "{cpu}%"
                    margin: 10
                    foreground: ddddddff
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: 
                    text: "{app-id}"
                    margin: 10
                    foreground: ddddddff
