[window]
opacity = 0.9
padding.x = 10
padding.y = 10
decorations = "Full"

[font]
normal.family = "0xProtoNerdFontMono"
bold.family = "0xProtoNerdFontMono"
italic.family = "0xProtoNerdFont"
bold_italic.family = "0xProtoNerdFontMono"
size = 15.0

