[window]
opacity = 0.9
padding.x = 10
padding.y = 10
decorations = "None"

[font]
normal.family = "BigBlueTerm437NerdFontMono"
bold.family = "BigBlueTerm437NerdFontMono"
italic.family = "BigBlueTerm437NerdFontMono"
bold_italic.family = "BigBlueTerm437NerdFontMono"
size = 10.0

